database:
    version: sqlite3
    path: resources/db.sqlite
    schema: resources/migration.sql

telegram:
    url: https://api.telegram.org/
    chat_id: some chat id
    token: some token
    send_message:
        parse_mode: Markdown

site:
    url: https://pikabu.ru/profile/
