database:
    name: pikabubot
    username: Admin_core
    password: core

telegram:
    url: https://api.telegram.org/
    chat_id: some chat id
    token: some token
    send_message:
        parse_mode: Markdown

migrations:
    path: /var/go/src/PikabuBot/resources/migrations

logger:
    type: syslog
